import Foundation

/// The slice of NSPasteboard this app needs, so the monitor can be tested
/// without touching the real system pasteboard.
public protocol PasteboardReading: AnyObject {
    /// Increments on every write by any app. The only change signal macOS gives us.
    var changeCount: Int { get }
    /// True when the owner asked clipboard managers not to store this content.
    var isConcealed: Bool { get }
    func readString() -> String?
}

#if canImport(AppKit)
import AppKit

extension NSPasteboard: PasteboardReading {
    /// Convention published at nspasteboard.org and honoured by password managers.
    public var isConcealed: Bool {
        let optOut: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        guard let types else { return false }
        return types.contains { optOut.contains($0.rawValue) }
    }

    public func readString() -> String? {
        string(forType: .string)
    }
}
#endif
